### ISSUE TITLE
helm chart: inbucket web console is not working

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket-community#20]
From https://github.com/inbucket/inbucket-community/pull/19#issuecomment-1821555102

> The inbucket web console is not working  with the default configuration because of unexisting `greeting.html` file.
I think if that greeting file is optional, the server should work. Or if that is mandatory, the container image should include a default file so the helm chart works out of the box?

**Comment by jhillyerd** [comment]
The docker startup tries to make a copy of greeting.html for users to customize if they wish:

https://github.com/inbucket/inbucket/blob/1b5a783dbd26677b3d73d38c7e7113dc12d4194a/etc/docker/defaults/start-inbucket.sh#L22

Is this not functioning in helm/k8s?

**Comment by corey-aloia** [comment]
@jhillyerd it looks like the code references ui/gretting.html as the default values for `INBUCKET_WEB_GREETINGFILE`. Maybe this is what it used to be? Anyway, I have opened a pr to set it to the correct value, and it is now working

**Comment by jhillyerd** [comment]
You are correct that the `ui/greeting.html` default is for running locally.

**Comment by corey-aloia** [comment]
@jhillyerd Great, in that case could you approve my pr https://github.com/inbucket/inbucket-community/pull/23
