### ISSUE TITLE
Can't configure SMTP TLS

### ISSUE THREAD

**Issue by micheljung** [inbucket/inbucket-community#42]
Correct me if I'm wrong, but it seems that SMTP TLS can't be configured, because `INBUCKET_SMTP_TLSPRIVKEY` and `INBUCKET_SMTP_TLSCERT` take a file name. However, the chart doesn't allow mounting a secret or config map. I know a persistent volume can be mounted, but that's not optimal.

**Comment by cpanato** [comment]
are you willing to open a PR to get that fixed?

**Comment by micheljung** [comment]
You mean like https://github.com/inbucket/inbucket-community/pull/43? ;)
